### ISSUE TITLE
"123 Moneys" does not work in English

### ISSUE THREAD

**Issue by Azarlak** [Ash031/Idling-Master#3]
`X Moneys` doesn't work in English due to money being an [uncountable noun](https://www.englishclub.com/grammar/nouns-countable-un.htm).

I can think of five ways of fixing this problem:
* **Option A**: Format it differently:
  * Always use: `Money: 123`
  * Never use: `123 Moneys`, `123 Money`, `Moneys: 123`
* **Option B**: Use a currency symbol.
  Some examples:
  * $ € ¤ £
* **Option C**: Use emoji.
  Some examples:
  * 💲 💰 💳 💵 💶 💷 💴 🎫 🎟️
* **Option D**: Use an icon or small image.
* **Option E**: Replace `Gold` with a countable noun instead.
  Some examples:
  * **Gold** _(Technically uncountable, but is accepted in games)_
    * 0 Gold, 1 Gold, 7 Gold
  * **Wealth** _(Technically uncountable, but is accepted in games)_
    * 0 Wealth, 1 Wealth, 7 Wealth
  * **Dollars** | **Credits** | **Funds**
    * 0 Funds, 1 Fund(s), 7 Funds
    0 Dollars, 1 Dollar(s), 7 Dollars
    0 Credits, 1 Credit(s), 7 Credits

Technically, there shouldn't be an "s" at the end of `Dollar | Credit | Fund` when you have _exactly 1_ of them, but handling that specific case would take a bit more effort, so ignoring that case and always including the "s" is relatively common and acceptable.

**Comment by Ash031** [comment]
I used moneys as a joke since it doesn't exist, but I can change it to gold since I use that term sometimes.

**Comment by Azarlak** [comment]
Well, using it as a joke could kinda work, but only if the rest of the game has consistently good English. Otherwise it might be difficult for players to know if it was intentional or a mistake.
