### ISSUE TITLE
Inconsistent clone assigment in Mine and Training

### ISSUE THREAD

**Issue by Azarlak** [Ash031/Idling-Master#6]
In the Training Area, clone assignment looks like this:
```
Skill: X clones assigned
[+(green)][-(red)]X% to next level
```

In the Mine Area, clone assignment looks like this:
```
Ore
[-(green)]X        [+(green)]
```

This is very inconsistent, and there are some changes I would like to see:
* Make the [-] buttons red in the Mine Area as well.
* Switch the sides of [-] and [+] in Mine or Training, so they're on the same sides in both Areas.
  * I would suggest [-] on the left, [+] on the right.
* If you want to have the number (X) between the buttons, it really should be centered, not left-aligned.
  * Some ways this could be done in case a simple `text-align: center;` doesn't work: a CSS flexbox, a CSS grid, or an HTML table with some CSS modifications.
* Add a `X per second` or `X/s` to the Mine Area to show how much of each ore you're gaining
* Optionally, but preferably: In the Training Area, change the positioning of `X clones assigned` and `X% to next level` to be more similar to the Mine Area.

In the end, I'd like to see something like this:
Training Area:
```
Skill(Level X): X% to next level
[-(red)]   X   [+(green)]
```
Mine Area:
```
Ore: X per second
[-(red)]   X   [+(green)]
```
You could also replace `Ore: X per second` with `Ore: X/s` if you think that looks better.

**Comment by Ash031** [comment]
Will Implement that in the next update. Thanks!
